ALTER TABLE "store_settings" ADD COLUMN IF NOT EXISTS "theme_config" jsonb DEFAULT '{"preset":"minimal","colors":{"primary":"#2563eb","surface1":"#ffffff","surface2":"#f8f9fa","surface3":"#f1f3f5","textPrimary":"#1a1a1a","textSecondary":"#6b7280","textTertiary":"#9ca3af","border":"#e5e7eb","borderHover":"#d1d5db","success":"#10b981","warning":"#f59e0b","error":"#ef4444"},"font":{"family":"IBM Plex Sans Arabic","url":"https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@300;400;500;600;700&display=swap","headingsSize":"1.5rem","bodySize":"1rem"},"layout":{"productCardColumns":4,"productCardStyle":"rounded","imageAspectRatio":"square","showRating":true,"showSalesCount":true,"showStockBadge":true,"showCategory":true,"showDiscountBadge":true},"homepage":{"showBanner":true,"showCategories":true,"showBestSellers":true,"showNewArrivals":true,"showTodayDeals":true,"showTrustBadges":true,"showMarketingBanner":true,"showFeaturedProducts":true,"sectionOrder":["banner","trust","categories","bestSellers","newArrivals","todayDeals","marketing","featured"]},"header":{"showAnnouncementBar":true,"announcementText":"","stickyHeader":true,"showSearch":true,"showCart":true,"showAccount":true},"footer":{"showPaymentLogos":true,"showSocialLinks":true,"showNewsletter":true,"companyDescription":""},"socialLinks":{"instagram":"","twitter":"","tiktok":"","snapchat":"","whatsapp":""},"customCss":"","analytics":{"googleTagManagerId":"","googleAnalyticsId":"","facebookPixelId":""}}'::jsonb;--> statement-breakpoint
CREATE INDEX "product_images_product_sort_idx" ON "product_images" USING btree ("product_id","sort_order");--> statement-breakpoint
CREATE INDEX "product_option_values_option_sort_idx" ON "product_option_values" USING btree ("product_option_id","sort_order");--> statement-breakpoint
CREATE INDEX "product_options_product_sort_idx" ON "product_options" USING btree ("product_id","sort_order");--> statement-breakpoint
CREATE INDEX "product_variants_product_sort_idx" ON "product_variants" USING btree ("product_id","sort_order");--> statement-breakpoint
CREATE INDEX "products_store_status_created_at_idx" ON "products" USING btree ("store_id","status","created_at");--> statement-breakpoint
CREATE INDEX "products_store_brand_idx" ON "products" USING btree ("store_id","brand_id");--> statement-breakpoint
CREATE INDEX "products_store_updated_at_idx" ON "products" USING btree ("store_id","updated_at");--> statement-breakpoint
CREATE INDEX "categories_store_active_sort_idx" ON "categories" USING btree ("store_id","is_active","sort_order");--> statement-breakpoint
CREATE INDEX "categories_store_parent_idx" ON "categories" USING btree ("store_id","parent_id");--> statement-breakpoint
CREATE INDEX "product_categories_product_idx" ON "product_categories" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "product_categories_category_idx" ON "product_categories" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "brands_store_active_sort_idx" ON "brands" USING btree ("store_id","is_active","sort_order");--> statement-breakpoint
CREATE INDEX "product_tags_product_idx" ON "product_tags" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "product_tags_tag_idx" ON "product_tags" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX "tags_store_sort_idx" ON "tags" USING btree ("store_id","sort_order");--> statement-breakpoint
CREATE INDEX "customer_addresses_customer_idx" ON "customer_addresses" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "customers_store_created_at_idx" ON "customers" USING btree ("store_id","created_at");--> statement-breakpoint
CREATE INDEX "customers_store_email_idx" ON "customers" USING btree ("store_id","email");--> statement-breakpoint
CREATE INDEX "cart_items_cart_idx" ON "cart_items" USING btree ("cart_id");--> statement-breakpoint
CREATE INDEX "cart_items_product_idx" ON "cart_items" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "carts_store_session_idx" ON "carts" USING btree ("store_id","session_token");--> statement-breakpoint
CREATE INDEX "carts_store_customer_idx" ON "carts" USING btree ("store_id","customer_id");--> statement-breakpoint
CREATE INDEX "carts_abandoned_updated_at_idx" ON "carts" USING btree ("is_abandoned","updated_at");--> statement-breakpoint
CREATE INDEX "carts_expires_at_idx" ON "carts" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "order_items_order_idx" ON "order_items" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "order_items_product_idx" ON "order_items" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "order_status_history_order_created_at_idx" ON "order_status_history" USING btree ("order_id","created_at");--> statement-breakpoint
CREATE INDEX "orders_store_created_at_idx" ON "orders" USING btree ("store_id","created_at");--> statement-breakpoint
CREATE INDEX "orders_store_status_created_at_idx" ON "orders" USING btree ("store_id","status","created_at");--> statement-breakpoint
CREATE INDEX "orders_store_payment_created_at_idx" ON "orders" USING btree ("store_id","payment_status","created_at");--> statement-breakpoint
CREATE INDEX "orders_store_fulfillment_created_at_idx" ON "orders" USING btree ("store_id","fulfillment_status","created_at");--> statement-breakpoint
CREATE INDEX "orders_customer_created_at_idx" ON "orders" USING btree ("customer_id","created_at");--> statement-breakpoint
CREATE INDEX "orders_store_external_idx" ON "orders" USING btree ("store_id","external_id");--> statement-breakpoint
CREATE INDEX "wallet_accounts_store_idx" ON "wallet_accounts" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "wallet_entries_store_created_at_idx" ON "wallet_entries" USING btree ("store_id","created_at");--> statement-breakpoint
CREATE INDEX "wallet_entries_store_status_created_at_idx" ON "wallet_entries" USING btree ("store_id","status","created_at");--> statement-breakpoint
CREATE INDEX "wallet_entries_account_created_at_idx" ON "wallet_entries" USING btree ("wallet_account_id","created_at");--> statement-breakpoint
CREATE INDEX "wallet_entries_reference_idx" ON "wallet_entries" USING btree ("reference_type","reference_id");--> statement-breakpoint
CREATE INDEX "webhook_deliveries_event_created_at_idx" ON "webhook_deliveries" USING btree ("webhook_event_id","created_at");--> statement-breakpoint
CREATE INDEX "webhook_deliveries_endpoint_created_at_idx" ON "webhook_deliveries" USING btree ("endpoint_id","created_at");--> statement-breakpoint
CREATE INDEX "webhook_deliveries_status_created_at_idx" ON "webhook_deliveries" USING btree ("status","created_at");--> statement-breakpoint
CREATE INDEX "webhook_endpoints_store_active_idx" ON "webhook_endpoints" USING btree ("store_id","is_active");--> statement-breakpoint
CREATE INDEX "webhook_events_status_created_at_idx" ON "webhook_events" USING btree ("status","created_at");--> statement-breakpoint
CREATE INDEX "webhook_events_store_created_at_idx" ON "webhook_events" USING btree ("store_id","created_at");--> statement-breakpoint
CREATE INDEX "webhook_events_type_created_at_idx" ON "webhook_events" USING btree ("event_type","created_at");--> statement-breakpoint
CREATE INDEX "notification_logs_store_sent_at_idx" ON "notification_logs" USING btree ("store_id","sent_at");--> statement-breakpoint
CREATE INDEX "notification_logs_store_status_sent_at_idx" ON "notification_logs" USING btree ("store_id","status","sent_at");--> statement-breakpoint
CREATE INDEX "channel_listings_store_status_idx" ON "channel_listings" USING btree ("store_id","status");--> statement-breakpoint
CREATE INDEX "channel_listings_connection_product_idx" ON "channel_listings" USING btree ("connection_id","product_id");--> statement-breakpoint
CREATE INDEX "channel_listings_product_idx" ON "channel_listings" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "channel_orders_store_created_at_idx" ON "channel_orders" USING btree ("store_id","created_at");--> statement-breakpoint
CREATE INDEX "channel_orders_connection_marketplace_order_idx" ON "channel_orders" USING btree ("connection_id","marketplace_order_id");--> statement-breakpoint
CREATE INDEX "channel_orders_local_order_idx" ON "channel_orders" USING btree ("local_order_id");--> statement-breakpoint
CREATE INDEX "marketplace_connections_status_last_sync_idx" ON "marketplace_connections" USING btree ("status","last_sync_at");--> statement-breakpoint
CREATE INDEX "sync_logs_store_created_at_idx" ON "sync_logs" USING btree ("store_id","created_at");--> statement-breakpoint
CREATE INDEX "sync_logs_connection_started_at_idx" ON "sync_logs" USING btree ("connection_id","started_at");--> statement-breakpoint
CREATE INDEX "sync_logs_status_started_at_idx" ON "sync_logs" USING btree ("status","started_at");