export const ORDER_STATUS_TRANSITIONS: Record<string, string[]> = {
  draft: ['checkout_started', 'pending_payment', 'cancelled'],
  checkout_started: ['pending_payment', 'cancelled'],
  pending_payment: ['confirmed', 'cancelled', 'refunded'],
  confirmed: ['processing', 'cancelled', 'refunded'],
  processing: ['ready_to_ship', 'ready_for_pickup', 'cancelled'],
  ready_to_ship: ['shipped', 'cancelled'],
  ready_for_pickup: ['picked_up', 'cancelled'],
  shipped: ['delivered', 'returned_to_sender', 'cancelled'],
  picked_up: [],
  delivered: ['completed', 'returned'],
  completed: ['returned', 'refunded'],
  cancelled: [],
  returned: ['refunded'],
  refunded: [],
  partially_refunded: ['refunded', 'completed'],
};

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  owner: [
    'stores:read', 'stores:update',
    'products:read', 'products:create', 'products:update', 'products:delete',
    'categories:manage',
    'brands:manage',
    'tags:manage',
    'orders:read', 'orders:update_status', 'orders:cancel', 'orders:refund',
    'customers:read',
    'wallet:read', 'wallet:request_payout',
    'wallet.payout.request', 'wallet.payout.review', 'wallet.payout.approve',
    'wallet.payout.reject', 'wallet.payout.mark_transferred',
    'wallet.payout.upload_proof', 'wallet.payout.verify_transfer',
    'wallet.payout.cancel', 'wallet.payout.reverse',
    'wallet.payout.view_all', 'wallet.payout.view_store',
    'shipping:manage',
    'settings:read', 'settings:update',
    'staff:manage',
    'reports:read',
    'coupons:read', 'coupons:create', 'coupons:update', 'coupons:delete',
    'promotions:read', 'promotions:create', 'promotions:update', 'promotions:delete',
    'exports:create', 'imports:create',
    'storefront:read',
    'compliance:read', 'compliance:write', 'compliance:submit', 'compliance:documents', 'compliance:review',
  ],
  manager: [
    'stores:read',
    'products:read', 'products:create', 'products:update', 'products:delete',
    'categories:manage',
    'brands:manage',
    'tags:manage',
    'orders:read', 'orders:update_status', 'orders:cancel',
    'customers:read',
    'wallet:read', 'wallet:request_payout',
    'shipping:manage',
    'settings:read', 'settings:update',
    'reports:read',
    'coupons:read', 'coupons:create', 'coupons:update', 'coupons:delete',
    'exports:create', 'imports:create',
    'storefront:read',
    'compliance:read',
  ],
  products_manager: [
    'products:read', 'products:create', 'products:update', 'products:delete',
    'categories:manage',
    'brands:manage',
    'tags:manage',
  ],
  orders_manager: [
    'orders:read', 'orders:update_status', 'orders:cancel',
    'customers:read',
    'shipping:manage',
  ],
  accountant: [
    'orders:read', 'orders:refund',
    'customers:read',
    'wallet:read', 'wallet:request_payout',
    'wallet.payout.view_store', 'wallet.payout.view_all',
    'reports:read',
    'exports:create',
  ],
  support: [
    'orders:read', 'orders:update_status',
    'customers:read',
    'products:read',
  ],
  viewer: [
    'stores:read',
    'products:read',
    'orders:read',
    'customers:read',
    'wallet:read',
    'reports:read',
  ],
};

export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;
