#!/usr/bin/env bash
# scripts/server/setup-deploy-user.sh (PR-K)
#
# One-time server hardening: creates a dedicated `deploy` user for CI/CD,
# then locks down SSH so root login and password auth are impossible.
#
# Prerequisites:
#   - Run as root on the staging server
#   - Have the CI SSH public key ready (copy from GitHub → Settings →
#     Environments → staging → STAGING_SSH_KEY → extract public key)
#   - After this script succeeds, update GitHub Secrets:
#       STAGING_USER  → deploy
#       STAGING_SSH_KEY → the private key that pairs with DEPLOY_PUBKEY
#
# Idempotent: safe to re-run (existing user / keys are preserved).
#
# Usage:
#   DEPLOY_PUBKEY="ssh-ed25519 AAAA... ci@github" bash setup-deploy-user.sh
#
set -euo pipefail

DEPLOY_USER="${DEPLOY_USER:-deploy}"
DEPLOY_PATH="${DEPLOY_PATH:-/srv/haa-stores}"

log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
ok()   { printf '  \033[0;32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[0;33m!\033[0m %s\n' "$*"; }
die()  { printf '\033[0;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# ─── Validate ────────────────────────────────────────────────────────────────
[ "$(id -u)" -eq 0 ] || die "Must run as root"

if [ -z "${DEPLOY_PUBKEY:-}" ]; then
  echo ""
  echo "  DEPLOY_PUBKEY is not set. Provide the CI SSH public key:"
  echo ""
  echo "    DEPLOY_PUBKEY=\"ssh-ed25519 AAAA... ci@github\" bash $0"
  echo ""
  echo "  To extract the public key from an existing STAGING_SSH_KEY private key:"
  echo "    ssh-keygen -y -f /tmp/staging_key"
  echo ""
  die "DEPLOY_PUBKEY must be set"
fi

# ─── 1. Create deploy user ────────────────────────────────────────────────────
log "1/5 Creating user: ${DEPLOY_USER}"
if id "$DEPLOY_USER" &>/dev/null; then
  ok "User ${DEPLOY_USER} already exists"
else
  useradd --system --create-home --shell /bin/bash "$DEPLOY_USER"
  ok "Created user ${DEPLOY_USER}"
fi

# ─── 2. SSH authorized key ────────────────────────────────────────────────────
log "2/5 Installing CI SSH public key"
DEPLOY_HOME=$(getent passwd "$DEPLOY_USER" | cut -d: -f6)
SSH_DIR="${DEPLOY_HOME}/.ssh"
AUTH_KEYS="${SSH_DIR}/authorized_keys"

install -d -m 0700 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "$SSH_DIR"
touch "$AUTH_KEYS"
chmod 0600 "$AUTH_KEYS"
chown "$DEPLOY_USER:$DEPLOY_USER" "$AUTH_KEYS"

if grep -qF "$DEPLOY_PUBKEY" "$AUTH_KEYS" 2>/dev/null; then
  ok "Key already in authorized_keys"
else
  echo "$DEPLOY_PUBKEY" >> "$AUTH_KEYS"
  ok "Key added to ${AUTH_KEYS}"
fi

# ─── 3. Docker access (no-password sudoers) ───────────────────────────────────
log "3/5 Granting docker access"
if getent group docker &>/dev/null; then
  usermod -aG docker "$DEPLOY_USER"
  ok "Added ${DEPLOY_USER} to docker group"
else
  warn "docker group not found — run bootstrap-staging-server.sh first"
fi

# Minimal sudoers: only docker and ss (needed for G7 port check)
SUDOERS_FILE="/etc/sudoers.d/90-${DEPLOY_USER}-deploy"
cat > "$SUDOERS_FILE" << SUDOERS
# Haa Stores — ${DEPLOY_USER} deploy privileges
# Generated by scripts/server/setup-deploy-user.sh
${DEPLOY_USER} ALL=(ALL) NOPASSWD: /usr/bin/docker, /usr/sbin/ss
SUDOERS
chmod 0440 "$SUDOERS_FILE"
visudo -cf "$SUDOERS_FILE" || die "Sudoers syntax error in ${SUDOERS_FILE}"
ok "Sudoers file: ${SUDOERS_FILE}"

# ─── 4. Deploy directory ownership ────────────────────────────────────────────
log "4/5 Setting deploy directory ownership"
if [ -d "$DEPLOY_PATH" ]; then
  chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "$DEPLOY_PATH"
  ok "Ownership set: ${DEPLOY_PATH} → ${DEPLOY_USER}"
else
  install -d -m 0755 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "$DEPLOY_PATH"
  ok "Created ${DEPLOY_PATH} (${DEPLOY_USER})"
fi

# ─── 5. SSH hardening ─────────────────────────────────────────────────────────
log "5/5 Hardening SSH daemon"
SSHD_CONF="/etc/ssh/sshd_config"
SSHD_DROP="/etc/ssh/sshd_config.d/99-haa-hardening.conf"

cat > "$SSHD_DROP" << 'SSHD'
# Haa Stores SSH hardening (PR-K)
# Inserted by scripts/server/setup-deploy-user.sh
PermitRootLogin no
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM no
SSHD
chmod 0644 "$SSHD_DROP"

# Validate config before restarting
if sshd -t 2>/dev/null; then
  systemctl reload sshd 2>/dev/null || systemctl restart sshd
  ok "SSH hardening applied and daemon reloaded"
  ok "  PermitRootLogin no"
  ok "  PasswordAuthentication no"
else
  warn "sshd config validation failed — hardening file written but daemon not reloaded"
  warn "Review ${SSHD_DROP} and reload manually: systemctl reload sshd"
fi

# ─── Summary ──────────────────────────────────────────────────────────────────
printf '\n\033[1;32m✓ PR-K complete\033[0m\n\n'
echo "  Deploy user:  ${DEPLOY_USER}"
echo "  Home:         ${DEPLOY_HOME}"
echo "  Auth keys:    ${AUTH_KEYS}"
echo "  Deploy path:  ${DEPLOY_PATH}"
echo "  SSH drop-in:  ${SSHD_DROP}"
echo ""
echo "  Next steps:"
echo "  1. Verify SSH access: ssh ${DEPLOY_USER}@<server> 'docker compose version'"
echo "  2. Update GitHub Secret STAGING_USER → ${DEPLOY_USER}"
echo "  3. Confirm root SSH is blocked: ssh root@<server>  (should fail)"
echo ""
