// PROBLEM-013 — ZATCA `<cbc:UUID>` must be a real UUIDv4, not INV-${orderId}.
//
// Background:
//   apps/api/src/routes/zatca.ts used to call buildZatcaInvoice with
//   `invoiceNumber: 'INV-' + orderId` and the invoice builder shoved
//   the SAME value into <cbc:UUID>. ZATCA Phase 2 portal validation
//   rejects anything that isn't a valid UUIDv4 there.
//
// Fix:
//   - ZatcaInvoiceInput gained an `invoiceUuid?: string` field.
//   - buildZatcaInvoice validates it via isValidInvoiceUuid(); if
//     missing / invalid, it generates a fresh crypto.randomUUID().
//   - The UUID lands in <cbc:UUID>, the human invoice number stays
//     in <cbc:ID>.
//   - ZatcaInvoiceResult now returns the resolved invoiceUuid so
//     callers can persist it (for stable reprints + PROBLEM-015
//     hash-chain wiring).
//   - Route passes randomUUID() explicitly.

import { describe, expect, it } from 'vitest';
import { buildZatcaInvoice, isValidInvoiceUuid } from '@haa/zatca-core';

const UUIDV4_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

const baseInput = {
  type: 'simplified' as const,
  transactionType: 'invoice' as const,
  invoiceNumber: 'INV-42',
  issueDate: '2026-06-23',
  issueTime: '10:00:00',
  seller: {
    name: 'متجر هاء',
    vatNumber: '300000000000003',
    address: {
      street: 'King Fahd Rd',
      city: 'Riyadh',
      postalCode: '12345',
      country: 'SA' as const,
    },
  },
  lineItems: [
    { name: 'منتج', quantity: 1, unitPrice: 100, vatRate: 0.15 },
  ],
};

describe('PROBLEM-013 — invoiceUuid is a real UUIDv4', () => {
  it('isValidInvoiceUuid accepts canonical UUIDv4 strings', () => {
    expect(isValidInvoiceUuid('d4e1b2a8-7c66-4eaa-9aae-1b1a8a3d51f4')).toBe(true);
    // Wrong version (v1, not v4)
    expect(isValidInvoiceUuid('d4e1b2a8-7c66-1eaa-9aae-1b1a8a3d51f4')).toBe(false);
    // INV-${orderId} must be rejected by the validator
    expect(isValidInvoiceUuid('INV-42')).toBe(false);
    // Empty / non-string
    expect(isValidInvoiceUuid('')).toBe(false);
    expect(isValidInvoiceUuid(undefined)).toBe(false);
    expect(isValidInvoiceUuid(null)).toBe(false);
  });

  it('buildZatcaInvoice mints a UUIDv4 when invoiceUuid is missing', () => {
    const r1 = buildZatcaInvoice(baseInput);
    const r2 = buildZatcaInvoice(baseInput);
    expect(r1.invoiceUuid).toMatch(UUIDV4_RE);
    expect(r2.invoiceUuid).toMatch(UUIDV4_RE);
    // Two calls without an explicit UUID must NOT collide.
    expect(r1.invoiceUuid).not.toEqual(r2.invoiceUuid);
  });

  it('buildZatcaInvoice rejects an invalid invoiceUuid (e.g. INV-prefixed) and mints a new one', () => {
    const r = buildZatcaInvoice({
      ...baseInput,
      invoiceUuid: 'INV-42', // legacy bad value
    });
    expect(r.invoiceUuid).toMatch(UUIDV4_RE);
    expect(r.invoiceUuid).not.toEqual('INV-42');
  });

  it('buildZatcaInvoice respects a caller-supplied valid UUIDv4', () => {
    const seed = 'd4e1b2a8-7c66-4eaa-9aae-1b1a8a3d51f4';
    const r = buildZatcaInvoice({ ...baseInput, invoiceUuid: seed });
    expect(r.invoiceUuid).toBe(seed);
  });

  it('<cbc:UUID> in the XML is the UUIDv4, <cbc:ID> is the invoiceNumber', () => {
    const seed = 'd4e1b2a8-7c66-4eaa-9aae-1b1a8a3d51f4';
    const r = buildZatcaInvoice({ ...baseInput, invoiceUuid: seed });
    expect(r.xmlContent).toContain(`<cbc:UUID>${seed}</cbc:UUID>`);
    expect(r.xmlContent).toContain('<cbc:ID>INV-42</cbc:ID>');
    // Critically: the UUID slot must NOT contain the bare INV- text.
    expect(r.xmlContent).not.toMatch(/<cbc:UUID>INV-/);
  });

  it('UUIDv4 generated by the builder satisfies the same validator', () => {
    const r = buildZatcaInvoice(baseInput);
    expect(isValidInvoiceUuid(r.invoiceUuid)).toBe(true);
  });
});

// Source-grep guard so future edits don't reintroduce the bug.
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

describe('PROBLEM-013 — source-grep guards', () => {
  const root = resolve(new URL('..', import.meta.url).pathname);

  it('packages/zatca-core/src/invoice.ts has no `<cbc:UUID>${input.invoiceNumber}', () => {
    const src = readFileSync(
      resolve(root, 'packages/zatca-core/src/invoice.ts'),
      'utf-8',
    );
    expect(src).not.toMatch(/<cbc:UUID>\$\{input\.invoiceNumber\}/);
    expect(src).toMatch(/<cbc:UUID>\$\{invoiceUuid\}/);
    expect(src).toMatch(/randomUUID/);
  });

  it('apps/api/src/routes/zatca.ts passes an explicit invoiceUuid via randomUUID', () => {
    const src = readFileSync(
      resolve(root, 'apps/api/src/routes/zatca.ts'),
      'utf-8',
    );
    expect(src).toMatch(/invoiceUuid:\s*randomUUID\(\)/);
  });
});
