import { pgTable, serial, varchar, integer, timestamp, boolean, text, decimal, jsonb, unique, uniqueIndex } from 'drizzle-orm/pg-core';
import { tenants } from './tenants.js';

export const stores = pgTable('stores', {
  id: serial('id').primaryKey(),
  tenantId: integer('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }),
  name: varchar('name', { length: 255 }).notNull(),
  slug: varchar('slug', { length: 100 }).notNull(),
  description: text('description'),
  logoUrl: varchar('logo_url', { length: 500 }),
  coverUrl: varchar('cover_url', { length: 500 }),
  primaryColor: varchar('primary_color', { length: 20 }).default('#5c9cd5'),
  backgroundColor: varchar('background_color', { length: 20 }).default('#ffffff'),
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 20 }),
  isDemo: boolean('is_demo').notNull().default(false),
  demoProfile: varchar('demo_profile', { length: 50 }),
  demoSeedVersion: varchar('demo_seed_version', { length: 50 }),
  status: varchar('status', { length: 20 }).notNull().default('active'),
  isActive: boolean('is_active').notNull().default(true),
  publishStatus: varchar('publish_status', { length: 20 }).notNull().default('draft'),
  seoTitle: varchar('seo_title', { length: 60 }),
  seoDescription: varchar('seo_description', { length: 160 }),
  city: varchar('city', { length: 100 }),
  district: varchar('district', { length: 100 }),
  street: varchar('street', { length: 255 }),
  postalCode: varchar('postal_code', { length: 20 }),
  latitude: decimal('latitude', { precision: 10, scale: 7 }),
  longitude: decimal('longitude', { precision: 10, scale: 7 }),
  policies: jsonb('policies').$type<{
    about?: string;
    privacy?: string;
    returns?: string;
    shipping?: string;
    terms?: string;
    contact?: string;
  }>(),
  // ربط دومين خارجي (QA Custom Domain): النطاق العاري المُطبّع + حالة التحقّق
  customDomain: varchar('custom_domain', { length: 253 }),
  customDomainStatus: varchar('custom_domain_status', { length: 20 }).notNull().default('none')
    .$type<'none' | 'pending' | 'verifying' | 'active' | 'failed'>(),
  customDomainToken: varchar('custom_domain_token', { length: 64 }),
  customDomainVerifiedAt: timestamp('custom_domain_verified_at'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (table) => ({
  uniqueSlug: unique().on(table.slug),
  // دومين مخصّص فريد عالمياً (يمنع اختطاف دومين متجرٍ آخر) — جزئي ليسمح بـ NULL متعدّد
  uniqueCustomDomain: uniqueIndex('stores_custom_domain_uniq').on(table.customDomain),
}));

export const storeSettings = pgTable('store_settings', {
  id: serial('id').primaryKey(),
  storeId: integer('store_id').notNull().references(() => stores.id),
  defaultCurrency: varchar('default_currency', { length: 3 }).default('SAR'),
  locale: varchar('locale', { length: 10 }).default('ar-SA'),
  direction: varchar('direction', { length: 3 }).default('rtl'),
  timezone: varchar('timezone', { length: 50 }).default('Asia/Riyadh'),
  weightUnit: varchar('weight_unit', { length: 5 }).default('g'),
  dimensionUnit: varchar('dimension_unit', { length: 5 }).default('cm'),
  orderPrefix: varchar('order_prefix', { length: 10 }).default('ORD-'),
  lowStockThreshold: integer('low_stock_threshold').default(5),
  themeConfig: jsonb('theme_config').default({
    preset: 'minimal',
    colors: {
      primary: '#5c9cd5',
      surface1: '#ffffff',
      surface2: '#f8f9fa',
      surface3: '#f1f3f5',
      textPrimary: '#1a1a1a',
      textSecondary: '#6b7280',
      textTertiary: '#9ca3af',
      border: '#e5e7eb',
      borderHover: '#d1d5db',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
    },
    font: {
      family: 'IBM Plex Sans Arabic',
      url: 'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@300;400;500;600;700&display=swap',
      headingsSize: '1.5rem',
      bodySize: '1rem',
    },
    layout: {
      productCardColumns: 4,
      productCardStyle: 'rounded',
      imageAspectRatio: 'square',
      showRating: true,
      showSalesCount: true,
      showStockBadge: true,
      showCategory: true,
      showDiscountBadge: true,
    },
    homepage: {
      showBanner: true,
      showCategories: true,
      showBestSellers: true,
      showNewArrivals: true,
      showTodayDeals: true,
      showTrustBadges: true,
      showMarketingBanner: true,
      showFeaturedProducts: true,
      sectionOrder: ['banner', 'trust', 'categories', 'bestSellers', 'newArrivals', 'todayDeals', 'marketing', 'featured'],
    },
    header: {
      showAnnouncementBar: true,
      announcementText: '',
      stickyHeader: true,
      showSearch: true,
      showCart: true,
      showAccount: true,
    },
    footer: {
      showPaymentLogos: true,
      showSocialLinks: true,
      showNewsletter: true,
      companyDescription: '',
    },
    socialLinks: {
      instagram: '',
      twitter: '',
      tiktok: '',
      snapchat: '',
      whatsapp: '',
    },
    customCss: '',
    analytics: {
      googleTagManagerId: '',
      googleAnalyticsId: '',
      facebookPixelId: '',
    },
  }),
  productFeatures: jsonb('product_features').$type<Record<string, boolean>>().default({
    imageLightbox: true,
    stickyCart: true,
    trustBadges: true,
    badgeMaroof: false,
    badgeSaudiBusinessCenter: false,
    badgeSaudiMade: false,
    reviews: true,
    shareButton: true,
    deliveryEstimate: true,
    sizeGuide: true,
    alsoBought: true,
    recentlyViewed: true,
    priceAlert: true,
    giftWrap: true,
    sendAsGift: true,
    pickup: true,
    stockBar: true,
    liveViewers: true,
    compareBadges: true,
  }),
  welcomeMessage: text('welcome_message'),
  welcomeMessageEnabled: boolean('welcome_message_enabled').default(false),
  preparationTime: integer('preparation_time').default(0),
  preparationTimeEnabled: boolean('preparation_time_enabled').default(false),
  minOrderAmount: decimal('min_order_amount', { precision: 14, scale: 2 }).default('0'),
  minOrderEnabled: boolean('min_order_enabled').default(false),
  giftWrapDefaultPrice: decimal('gift_wrap_default_price', { precision: 12, scale: 2 }).default('0'),
  giftMessageMaxLength: integer('gift_message_max_length').default(250),
  giftWrapInstructions: text('gift_wrap_instructions'),
  pickupInstructions: text('pickup_instructions'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});
