/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          950: 'var(--color-primary-950)',
        },
        surface: {
          1: 'var(--surface-1)',
          2: 'var(--surface-2)',
          3: 'var(--surface-3)',
          inverse: 'var(--surface-inverse)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          disabled: 'var(--text-disabled)',
          link: 'var(--text-link)',
        },
        border: {
          DEFAULT: 'var(--border-default)',
          hover: 'var(--border-hover)',
          focus: 'var(--border-focus)',
          disabled: 'var(--border-disabled)',
        },
        success: 'var(--color-success)',
        'success-soft': 'var(--color-success-subtle)',
        'success-text': 'var(--color-success-text)',
        warning: 'var(--color-warning)',
        'warning-soft': 'var(--color-warning-subtle)',
        'warning-text': 'var(--color-warning-text)',
        danger: 'var(--color-danger)',
        'danger-soft': 'var(--color-danger-subtle)',
        'danger-text': 'var(--color-danger-text)',
        info: 'var(--color-info)',
        'info-soft': 'var(--color-info-subtle)',
        'info-text': 'var(--color-info-text)',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      borderRadius: {
        none: '0',
        xs: 'var(--radius-xs, 6px)',
        sm: 'var(--radius-sm, 8px)',
        md: 'var(--radius-md, 12px)',
        lg: 'var(--radius-lg, 20px)',
        xl: 'var(--radius-xl, 24px)',
        '2xl': 'var(--card-radius, 16px)',
        card: 'var(--card-radius, 16px)',
        modal: 'var(--radius-modal, 24px)',
        pill: 'var(--radius-pill, 9999px)',
        badge: 'var(--badge-radius, 9999px)',
      },
      spacing: {
        '0': 'var(--spacing-0)',
        '1': 'var(--spacing-1)',
        '2': 'var(--spacing-2)',
        '3': 'var(--spacing-3)',
        '4': 'var(--spacing-4)',
        '5': 'var(--spacing-5)',
        '6': 'var(--spacing-6)',
        '8': 'var(--spacing-8)',
        '10': 'var(--spacing-10)',
        '12': 'var(--spacing-12)',
      },
      fontSize: {
        'xs': ['var(--text-xs, 12px)', { lineHeight: '16px' }],
        'sm': ['var(--text-sm, 13px)', { lineHeight: '18px' }],
        'base': ['var(--text-base, 14px)', { lineHeight: '20px' }],
        'md': ['var(--text-md, 15px)', { lineHeight: '22px' }],
        'product-title': ['var(--product-title-size, 14px)', { lineHeight: '20px' }],
        'product-price': ['var(--product-price-size, 16px)', { lineHeight: '22px' }],
        'section-title': ['var(--section-title-size, 18px)', { lineHeight: '24px' }],
        'page-title': ['var(--page-title-size, 24px)', { lineHeight: '32px' }],
        'hero-title': ['var(--hero-title-size, 32px)', { lineHeight: '40px' }],
      },
      boxShadow: {
        xs: 'var(--shadow-xs, 0 1px 2px rgb(0 0 0 / 0.04))',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        card: 'var(--shadow-card, 0 2px 8px rgb(0 0 0 / 0.06))',
        'card-hover': 'var(--shadow-card-hover, 0 8px 24px rgb(0 0 0 / 0.08))',
        popover: 'var(--shadow-popover, 0 4px 16px rgb(0 0 0 / 0.1))',
        modal: 'var(--shadow-modal, 0 16px 48px rgb(0 0 0 / 0.15))',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'carousel': 'carousel 20s linear infinite',
        'carousel-fast': 'carousel 12s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        carousel: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      zIndex: {
        base: 'var(--z-base)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        overlay: 'var(--z-overlay)',
        modal: 'var(--z-modal)',
        toast: 'var(--z-toast)',
        tooltip: 'var(--z-tooltip)',
      },
    },
  },
  plugins: [
    function ({ addUtilities }) {
      addUtilities({
        '.scrollbar-hide': {
          '-ms-overflow-style': 'none',
          'scrollbar-width': 'none',
          '&::-webkit-scrollbar': { display: 'none' },
        },
      });
    },
  ],
};
