/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--color-primary, var(--brand-primary, #2a6fb8))',
          50: 'var(--color-primary-50, color-mix(in srgb, var(--brand-primary, #2a6fb8) 8%, #fff))',
          100: 'var(--color-primary-100, color-mix(in srgb, var(--brand-primary, #2a6fb8) 14%, #fff))',
          200: 'var(--color-primary-200, color-mix(in srgb, var(--brand-primary, #2a6fb8) 26%, #fff))',
          300: 'var(--color-primary-300, color-mix(in srgb, var(--brand-primary, #2a6fb8) 42%, #fff))',
          400: 'var(--color-primary-400, color-mix(in srgb, var(--brand-primary, #2a6fb8) 64%, #fff))',
          500: 'var(--color-primary-500, var(--brand-primary, #2a6fb8))',
          600: 'var(--color-primary-600, color-mix(in srgb, var(--brand-primary, #2a6fb8) 88%, #000))',
          700: 'var(--color-primary-700, color-mix(in srgb, var(--brand-primary, #2a6fb8) 76%, #000))',
          800: 'var(--color-primary-800, color-mix(in srgb, var(--brand-primary, #2a6fb8) 60%, #000))',
          900: 'var(--color-primary-900, color-mix(in srgb, var(--brand-primary, #2a6fb8) 42%, #000))',
          950: 'var(--color-primary-950, color-mix(in srgb, var(--brand-primary, #2a6fb8) 24%, #000))',
          soft: 'var(--color-primary-soft, color-mix(in srgb, var(--brand-primary, #2a6fb8) 14%, #fff))',
          foreground: '#ffffff',
        },
        surface: {
          DEFAULT: '#ffffff',
          1: '#ffffff',
          2: '#f9fafb',
          3: '#f3f4f6',
          inverse: '#111827',
        },
        text: {
          primary: '#111827',
          secondary: '#4b5563',
          tertiary: '#6b7280',
          disabled: '#d1d5db',
          link: 'var(--text-link, #58a1e2)',
        },
        border: {
          subtle: 'var(--border-subtle)',
          DEFAULT: 'var(--border-default)',
          hover: 'var(--border-hover)',
          focus: 'var(--border-focus)',
          disabled: 'var(--border-disabled)',
        },
        success: '#16a34a',
        'success-soft': '#f0fdf4',
        'success-text': '#15803d',
        warning: '#f59e0b',
        'warning-soft': '#fffbeb',
        'warning-text': '#b45309',
        danger: '#dc2626',
        'danger-soft': '#fef2f2',
        'danger-text': '#b91c1c',
        info: 'var(--color-info, #2a6fb8)',
        'info-soft': 'var(--color-info-subtle, #eef5fc)',
        'info-text': 'var(--color-info-text, #3d8ad4)',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      borderRadius: {
        none: '0',
        xs: 'var(--radius-xs, 6px)',
        sm: 'var(--radius-sm, 8px)',
        md: 'var(--radius-md, 12px)',
        lg: 'var(--radius-lg, 20px)',
        xl: 'var(--radius-xl, 24px)',
        '2xl': 'var(--card-radius, 16px)',
        '3xl': 'var(--radius-3xl, 24px)',
        card: 'var(--card-radius, 16px)',
        modal: 'var(--radius-modal, 24px)',
        pill: 'var(--radius-pill, 9999px)',
        badge: 'var(--badge-radius, 9999px)',
      },
      spacing: {
        '0': 'var(--space-0, 0px)',
        '1': 'var(--space-1, 4px)',
        '2': 'var(--space-2, 8px)',
        '3': 'var(--space-3, 12px)',
        '4': 'var(--space-4, 16px)',
        '5': 'var(--space-5, 20px)',
        '6': 'var(--space-6, 24px)',
        '7': 'var(--space-7, 28px)',
        '8': 'var(--space-8, 32px)',
        '9': 'var(--space-9, 36px)',
        '10': 'var(--space-10, 40px)',
        '11': 'var(--space-11, 44px)',
        '12': 'var(--space-12, 48px)',
        '14': 'var(--space-14, 56px)',
        '16': 'var(--space-16, 64px)',
        '20': 'var(--space-20, 80px)',
        '24': 'var(--space-24, 96px)',
        '28': 'var(--space-28, 112px)',
        '32': 'var(--space-32, 128px)',
        '36': 'var(--space-36, 144px)',
        '40': 'var(--space-40, 160px)',
        '48': 'var(--space-48, 192px)',
        '56': 'var(--space-56, 224px)',
        '64': 'var(--space-64, 256px)',
        '72': 'var(--space-72, 288px)',
        '80': 'var(--space-80, 320px)',
        '96': 'var(--space-96, 384px)',
      },
      fontSize: {
        '2xs': ['var(--text-2xs, 10px)', { lineHeight: '14px' }],
        'xs': ['var(--text-xs, 12px)', { lineHeight: '16px' }],
        'sm': ['var(--text-sm, 13px)', { lineHeight: '18px' }],
        'base': ['var(--text-base, 14px)', { lineHeight: '20px' }],
        'md': ['var(--text-md, 15px)', { lineHeight: '22px' }],
        'lg': ['var(--text-lg, 18px)', { lineHeight: '28px' }],
        'xl': ['var(--text-xl, 20px)', { lineHeight: '28px' }],
        '2xl': ['var(--text-2xl, 24px)', { lineHeight: '32px' }],
        '3xl': ['var(--text-3xl, 30px)', { lineHeight: '36px' }],
        '4xl': ['var(--text-4xl, 36px)', { lineHeight: '40px' }],
        '5xl': ['var(--text-5xl, 48px)', { lineHeight: '1' }],
        '6xl': ['var(--text-6xl, 60px)', { lineHeight: '1' }],
        '7xl': ['var(--text-7xl, 72px)', { lineHeight: '1' }],
        '8xl': ['var(--text-8xl, 96px)', { lineHeight: '1' }],
        'product-title': ['var(--product-title-size, 14px)', { lineHeight: '20px' }],
        'product-price': ['var(--product-price-size, 16px)', { lineHeight: '22px' }],
        'section-title': ['var(--section-title-size, 18px)', { lineHeight: '24px' }],
        'page-title': ['var(--page-title-size, 24px)', { lineHeight: '32px' }],
        'hero-title': ['var(--hero-title-size, 32px)', { lineHeight: '40px' }],
      },
      letterSpacing: {
        eyebrow: '0.12em',
      },
      boxShadow: {
        xs: 'var(--shadow-xs, 0 1px 2px rgb(0 0 0 / 0.04))',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
        card: 'var(--shadow-card, 0 2px 8px rgb(0 0 0 / 0.06))',
        'card-hover': 'var(--shadow-card-hover, 0 8px 24px rgb(0 0 0 / 0.08))',
        popover: 'var(--shadow-popover, 0 4px 16px rgb(0 0 0 / 0.1))',
        modal: 'var(--shadow-modal, 0 16px 48px rgb(0 0 0 / 0.15))',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'carousel': 'carousel 20s linear infinite',
        'carousel-fast': 'carousel 12s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        carousel: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      zIndex: {
        base: 'var(--z-base)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        overlay: 'var(--z-overlay)',
        modal: 'var(--z-modal)',
        toast: 'var(--z-toast)',
        tooltip: 'var(--z-tooltip)',
      },
    },
  },
  plugins: [
    function ({ addUtilities }) {
      addUtilities({
        '.scrollbar-hide': {
          '-ms-overflow-style': 'none',
          'scrollbar-width': 'none',
          '&::-webkit-scrollbar': { display: 'none' },
        },
      });
    },
  ],
};
